FROM --platform=linux/amd64 ubuntu:22.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential libboost-program-options-dev

COPY . /repo
WORKDIR /repo/data/data_conv/dna
RUN make -j8

FROM ubuntu:22.04 as package
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y libboost-program-options-dev
COPY --from=builder /repo/data/data_conv/dna/sample_dna_substr /
